export const GET_DOGS = 'GET_DOGS';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
export const GET_DOG_BY_ID = 'GET_DOG_BY_ID';
export const GET_DOG_BY_QUERY = 'GET_DOG_BY_QUERY';
export const SORTED_BY_WEIGHT = 'SORTED_BY_WEIGHT';
export const SORTED_BY_NAME = 'SORTED_BY_NAME';
export const FILTERED_BY_TEMPERAMENT = 'FILTERED_BY_TEMPERAMENT';